name: 'Provision t2.micro EC2'

on:
  workflow_dispatch:
    inputs:
        ec2_name:
          description: EC2 name
          required: true
          default: 'App Server'
          type: string

jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: '${{secrets.TERRAFORM_EC2_AK}}'
          aws-secret-access-key: '${{secrets.TERRAFORM_EC2_SK}}'
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wraper: false
      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_ec2_name: "${{github.event.inputs.ec2_name}}"
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
        